version: '3.9'
services:
  autoshutdown: 
    build: .
    image: duplocloud/autoshutdown-function:latest
    container_name: autoshutdown
    ports:
    - 9000:8080
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
